Simple-Hospital-Database-Website/Course_Project/Course_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('HospitalsApp/', include('HospitalsApp.urls')),
]

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/urls.py
# import path function from django.urls
from django.urls import path

# import views.py from the current folder
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('home/', views.homepage, name='homepage'),
    path('add/', views.add_new_hospital, name='add_new_student'),
    path('list/', views.list_hospitals, name='list_hospitals'),
    path('list/<str:pk>', views.list_hospitals, name='list_hospitals'),
    path('search/', views.search_hospital, name='search_hospital'),
    path('update/', views.update_hospital, name='update_hospital'),
    path('update/<str:pk>', views.update_hospital, name='update_hospital'),
    path('delete/', views.delete_hospital, name='delete_hospital'),
    path('delete/<str:pk>', views.delete_hospital, name='delete_hospital'),
    path('registration/', views.registration_page, name='registration'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('email/', views.email, name='email'),
]

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/models.py
from django.db import models
from .validate import validate_name, validate_zip_code, validate_phone, validate_type
from django.core.validators import validate_email

# Create your models here.
class Hospital(models.Model):
    name     = models.CharField(primary_key=True, null=False, blank=False, max_length=100, validators=[validate_name])
    zip_code = models.CharField(null=False, blank=False, max_length=10, validators=[validate_zip_code])
    phone    = models.CharField(null=False, blank=False, max_length=12, validators=[validate_phone])
    type     = models.CharField(max_length=9, validators=[validate_type])
    email    = models.CharField(null=False, blank=False, max_length=50, validators=[validate_email])
    visible  = models.BooleanField(default=True)
    def __str__(self):
        return f'{self.name}:{self.zip_code}:{self.phone}:{self.type}:{self.email}:{self.visible}'

class MyEmail(models.Model):
    password = models.CharField(null=False, blank=False, max_length=50)
    receiver = models.CharField(null=False, blank=False, max_length=254, validators=[validate_email])
    subject  = models.CharField(null=False, blank=False, max_length=50)
    message  = models.CharField(null=False, blank=False, max_length=2000)
    def __str__(self):
        return f'{self.password}:{self.receiver}:{self.subject}:{self.message}'

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/forms.py
from django import forms
from .models import Hospital, MyEmail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import re

class NewHospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['name', 'zip_code', 'phone', 'type', 'email']

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Example Hospital'}),
            'zip_code': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Canadian or American'}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'234-567-8901'}),
            'type': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Public/Private/Nonprofit'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'someone@example.ca'}),
        }

class SendEmailForm(forms.ModelForm):

    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'Enter your Email Password'})
    )

    class Meta:
        model = MyEmail
        fields = ['password', 'receiver', 'subject', 'message']

        widgets = {
            'receiver': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter the Receiver\'s Email'}),
            'subject': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter the Subject'}),
            'message': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Enter a Message'}),
        }

class CreateUserForm(UserCreationForm):

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'})
    )
    password2 = forms.CharField(
        label='Confirm password',
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'})
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control', 'placeholder':'fbob'}),
            'first_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Fred'}),
            'last_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Bob'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'someone@example.ca'}),
        }

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import authenticated_user, allowed_user
from .forms import NewHospitalForm, SendEmailForm
from .models import Hospital
from django.db.models import Q
from .forms import CreateUserForm
from django.contrib.auth.models import Group
from django.contrib.auth import login, logout, authenticate
import re
import smtplib
from email.message import EmailMessage

# Create your views here.
@login_required(login_url='login')
def homepage(request):
    return render(request, 'home.html')

@login_required(login_url='login')
@allowed_user(allowed_groups=['Admins'])
def add_new_hospital(request):
    if request.method == 'POST':
        form = NewHospitalForm(request.POST)
        if form.is_valid():
            modified = form.save(commit=False)

            # Zip code reformatting.
            if re.match(r'^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]-\d[ABCEGHJ-NPRSTV-Z]\d$', modified.zip_code, re.IGNORECASE): # e.g. t8V-4c4 -> T8V4C4
                modified.zip_code = modified.zip_code[:3].upper() + modified.zip_code[4:].upper()
            elif re.match(r'^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z] \d[ABCEGHJ-NPRSTV-Z]\d$', modified.zip_code, re.IGNORECASE): # e.g. T8V 4c4 -> T8V4C4
                modified.zip_code = modified.zip_code[:3].upper() + modified.zip_code[4:].upper()
            elif re.match(r'^[0-9]{5}(?:-[0-9]{4})$', modified.zip_code): # e.g. 12345-6789 -> 123456789
                modified.zip_code = modified.zip_code[:5] + modified.zip_code[6:]
            elif re.match(r'^[0-9]{5}(?: [0-9]{4})$', modified.zip_code): # e.g. 12345 6789 -> 123456789
                modified.zip_code = modified.zip_code[:5] + modified.zip_code[6:]

            # Type reformatting.
            modified.type = modified.type[0].upper() + modified.type[1:].lower() # e.g. prIVaTe -> Private
            
            modified.save()
            form.save_m2m()
            messages.success(request, ('A new hospital was added successfully!'))
            return redirect('homepage')
        else:
            messages.error(request, ('Failed to add a new hospital! One of more of the fields have issues.'))
            return render(request, 'add.html', {'form' : form})
    form = NewHospitalForm()
    return render(request, 'add.html', {'form' : form})

@login_required(login_url='login')
def list_hospitals(request, pk=None):
    hospital_list = Hospital.objects.all().order_by('name')
    if pk is not None:
        hospital_list = Hospital.objects.filter(pk=pk)
        messages.success(request, (f'Viewing {pk}'))
    return render(request, 'list.html', {'hospital_list' : hospital_list})

@login_required(login_url='login')
def search_hospital(request):
    if request.method == 'POST':
        response = request.POST['response'].strip()
        searchFilter = request.POST['searchFilter']

        if searchFilter == 'name':
            hospital_list = Hospital.objects.filter(name__contains=response).order_by('name')
            if hospital_list.count() == 0:
                messages.error(request, ('There are no hospitals associated with that name!'))
                return render(request, 'search.html')
            messages.success(request, ('Search was successful!'))
            return render(request, 'list.html', {'hospital_list' : hospital_list})
        
        elif searchFilter == 'zipcode':
            if ' ' in response or '-' in response:
                temp = ''
                for i in range(len(response)):
                    if response[i] != ' ' and response[i] != '-':
                        temp += response[i]
                response = temp
            hospital_list = Hospital.objects.filter(zip_code__contains=response).order_by('name')
            if hospital_list.count() == 0:
                messages.error(request, ('There are no hospitals associated with that zip code!'))
                return render(request, 'search.html')
            messages.success(request, ('Search was successful!'))
            return render(request, 'list.html', {'hospital_list' : hospital_list})
        
        elif searchFilter == 'phone':
            temp = ''
            for i in range(len(response)):
                if response[i] != '(' and response[i] != ')' and response[i] != ' ' and response[i] != '-':
                    temp += response[i]
            temp3 = temp
            if len(temp) > 3:
                temp = temp[:3] + '-' + temp[3:]
            temp2 = temp
            if len(temp) > 7:
                temp = temp[:7] + '-' + temp[7:]
            hospital_list = Hospital.objects.filter(Q(phone__contains=temp) | Q(phone__contains=temp2) | Q(phone__contains=temp3)).order_by('name')
            if hospital_list.count() == 0:
                messages.error(request, ('There are no hospitals associated with that phone number!'))
                return render(request, 'search.html')
            messages.success(request, ('Search was successful!'))
            return render(request, 'list.html', {'hospital_list' : hospital_list})
        
        elif searchFilter == 'type':
            hospital_list = Hospital.objects.filter(type__startswith=response).order_by('name')
            if hospital_list.count() == 0:
                messages.error(request, ('There are no hospitals with that type!'))
                return render(request, 'search.html')
            messages.success(request, ('Search was successful!'))
            return render(request, 'list.html', {'hospital_list' : hospital_list})
        
        elif searchFilter == 'email':
            hospital_list = Hospital.objects.filter(email__startswith=response).order_by('name')
            if hospital_list.count() == 0:
                messages.error(request, ('There are no hospitals associated with that email!'))
                return render(request, 'search.html')
            messages.success(request, ('Search was successful!'))
            return render(request, 'list.html', {'hospital_list' : hospital_list})
        
    return render(request, 'search.html')

@login_required(login_url='login')
@allowed_user(allowed_groups=['Admins'])
def update_hospital(request, pk=None): # Need to implement
    if request.method == 'POST':
        pk = request.POST['pk']
        if 'update' in request.POST:
            name = request.POST['name']
            zip_code = request.POST['zip_code']
            phone = request.POST['phone']
            myType = request.POST['type']
            email = request.POST['email']

            # Zip code reformatting.
            if re.match(r'^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]-\d[ABCEGHJ-NPRSTV-Z]\d$', zip_code, re.IGNORECASE): # e.g. t8V-4c4 -> T8V4C4
                zip_code = zip_code[:3].upper() + zip_code[4:].upper()
            elif re.match(r'^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z] \d[ABCEGHJ-NPRSTV-Z]\d$', zip_code, re.IGNORECASE): # e.g. T8V 4c4 -> T8V4C4
                zip_code = zip_code[:3].upper() + zip_code[4:].upper()
            elif re.match(r'^[0-9]{5}(?:-[0-9]{4})$', zip_code): # e.g. 12345-6789 -> 123456789
                zip_code = zip_code[:5] + zip_code[6:]
            elif re.match(r'^[0-9]{5}(?: [0-9]{4})$', zip_code): # e.g. 12345 6789 -> 123456789
                zip_code = zip_code[:5] + zip_code[6:]

            # Type reformatting.
            myType = myType[0].upper() + myType[1:].lower() # e.g. prIVaTe -> Private

            hospital_entry = Hospital.objects.filter(name=pk).update(name=name, zip_code=zip_code, phone=phone, type=myType, email=email)
            messages.success(request, ('Successfully updated the chosen Hospital!'))
            return redirect('homepage')
        elif 'cancel' in request.POST:
            messages.error(request, (f'{pk} was not changed!'))
            return redirect('homepage')

    if pk is None:
        return redirect('homepage')
    hospital_entry = Hospital.objects.get(name=pk)
    return render(request, 'update.html', {'hospital' : hospital_entry})

@login_required(login_url='login')
@allowed_user(allowed_groups=['Admins'])
def delete_hospital(request, pk=None):
    if request.method == 'POST':
        if 'yes' in request.POST:
            Hospital.objects.filter(pk=pk).update(visible=False)
            messages.success(request, (f'{pk} was successfully deleted!'))
            return redirect('homepage')
        elif 'no' in request.POST:
            messages.error(request, (f'{pk} was not deleted!'))
            return redirect('homepage')
    if pk is None:
        return redirect('homepage')
    return render(request, 'delete.html', {'pk' : pk})

@authenticated_user
def registration_page(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            if (first_name and not first_name.isalpha()) or (last_name and not last_name.isalpha()):
                messages.error(request, ('Please enter a valid alphabetic name!'))
                return render(request, 'registration.html', {'form' : form})
            else:
                newuser = form.save()
                user = form.cleaned_data.get('username')
                group = Group.objects.get(name='Users')
                newuser.groups.add(group)
                messages.success(request, f'A new user account was created for {user}')
                return redirect('login')
        else:
            messages.error(request, ('Form has invalid fields!'))
            return render(request, 'registration.html', {'form' : form})
    form = CreateUserForm()
    return render(request, 'registration.html', {'form' : form})

@authenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/add.html
{% extends "auth_layout.html" %}
{% load static %}

{% block jsscripts %}
    <script src="{% static 'scripts/addUpdate.js' %}"></script>
{% endblock jsscripts %}

{% block content %}
    <h1>Add a New Hospital</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="col-md-4 text-center offset-md-4">
        <fieldset id="panel">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% for field in form %}
                    {% if field != visible %}
                        <div class="row g-3 align-items">
                            <div class="col-auto" >
                                <label for="{{ field.label|lower }}" class="form-label">
                                    {{ field.label }}
                                </label>
                            </div>
                            <div class="col-12">
                                {{ field }}<br/>
                            </div>
                        </div>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
                <a href="/HospitalsApp/home" class="btn btn-secondary" role="button" aria-pressed="true"><i class="bi bi-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success"><i class="bi bi-database-add"></i> Add</button>
            </form>
        </fieldset>
    </div>
{% endblock content %}

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/auth_layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hospital Database</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %} ">

    {% block jsscripts %}{% endblock jsscripts %}
</head>

<body>
  <nav class="navbar navbar-expand navbar-dark">
    <a class="navbar-brand" href="/HospitalsApp/home"><img src="{% static 'images/icon.png' %}" width="30" height="30" class="d-inline-block align-top">Hospital Database</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/HospitalsApp/home">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/HospitalsApp/add">Add Hospital</a>
            <a class="dropdown-item" href="/HospitalsApp/list">List Hospitals</a>
            <a class="dropdown-item" href="/HospitalsApp/search">Search Hospital(s)</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link">Welcome {{ request.user }}</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link">{{ request.user.email }}</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/HospitalsApp/email">Email</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
      </ul>
      <!--
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search"> 
        </form>
      -->
    </div>
  </nav>

  <div class="col-md-12">
    {% block content %}{% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/delete.html
{% extends "auth_layout.html" %}

{% block content %}
    <h1>Delete an Existing Hospital</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="col-md-4 text-center offset-md-4">
        <fieldset id="panel">
            <form action="" method="post" class="form">
                {% csrf_token %}
                <div class="row g-3 align-items">
                    <div class="col-12">
                        <label>Are you sure you want to delete {{ pk }}?</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-danger" value="Yes" name="yes"><i class="bi bi-trash"></i> Yes</button>
                <button type="submit" class="btn btn-secondary" value="No" name="no"><i class="bi bi-x-square"></i> No</button>
            </form>
        </fieldset>
    </div>

{% endblock content %}

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/email.html
{% extends "auth_layout.html" %}
{% load static %}

{% block jsscripts %}
    <script src="{% static 'scripts/email.js' %}"></script>
{% endblock jsscripts %}

{% block content %}
    <h1>Email</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="container mx-auto p-3">
        <fieldset id="panel">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% for field in form %}
                    {% if field != visible %}
                        <div class="row g-3 align-items">
                            <div class="col-auto">
                                <label for="{{ field.label|lower }}" class="form-label">
                                    {{ field.label }}
                                </label>
                            </div>
                            <div class="col-12">
                                {{ field }}<br/>
                            </div>
                        </div>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
                <input type="hidden" name="emailAddress" value="{{ request.user.email }}">
                <a href="/HospitalsApp/home" class="btn btn-secondary" role="button" aria-pressed="true"><i class="bi bi-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success"><i class="bi bi-send"></i> Send</button>
            </form>
        </fieldset>
    </div>
{% endblock content %}

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/home.html
{% extends "auth_layout.html" %}
{% block content %}
    <h1>Hospital Database</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="col-md-4 text-center offset-md-4">
        <fieldset id="panel">
            <div class="row g-3 align-items">
                <div class="col-12" id="panel">
                    <a href="/HospitalsApp/add" class="w-100 btn btn-primary btn-lg" role="button" aria-pressed="true">Add a New Hospital</a>
                </div>
            </div>
            <div class="row g-3 align-items">
                <div class="col-12" id="panel">
                    <a href="/HospitalsApp/list" class="w-100 btn btn-success btn-lg" role="button" aria-pressed="true">List All Hospitals</a>
                </div>
            </div>
            <div class="row g-3 align-items">
                <div class="col-12" id="panel">
                    <a href="/HospitalsApp/search" class="w-100 btn btn-danger btn-lg" role="button" aria-pressed="true">Search for Hospital(s)</a>
                </div>
            </div>
        </fieldset>
    </div>
{% endblock content %}

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/login.html
{% extends "layout.html" %}
{% load static %}

{% block jsscripts %}
    <script src="{% static 'scripts/login.js' %}"></script>
{% endblock jsscripts %}

{% block content %}
    <h1>User Login Page</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="col-md-4 text-center offset-md-4">
        <fieldset id="panel">
            <form method="post" accept="">
                {% csrf_token %}
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="username" class="form-label">
                            Username
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Enter your Username" required><br/>
                    </div>
                </div>
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="password" class="form-label">
                            Password
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter your Password" required><br/>
                    </div>
                </div>
                <button type="submit" class="btn btn-success"><i class="bi bi-box-arrow-in-right"></i> Login</button>
                <a href="/HospitalsApp/registration" class="btn btn-primary" role="button" aria-pressed="true"><i class="bi bi-person-add"></i> Register</a>
            </form>
        </fieldset>
    </div>
{% endblock content %}

Simple-Hospital-Database-Website/Course_Project/HospitalsApp/templates/update.html
{% extends "auth_layout.html" %}
{% load static %}

{% block jsscripts %}
    <script src="{% static 'scripts/addUpdate.js' %}"></script>
{% endblock jsscripts %}

{% block content %}
    <h1>Update a Hospital</h1>
    {% if messages %}
        <br/>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% else %}
                <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="col-md-4 text-center offset-md-4">
        <fieldset id="panel">
            <form action="" method="post" class="form">
                {% csrf_token %}
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="name" class="form-label">
                            Name
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" name="name" class="form-control" placeholder="Example Hospital" maxlength="100" required id="id_name" value="{{ hospital.name }}"><br/>
                    </div>
                </div>
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="zip code" class="form-label">
                            Zip code
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" name="zip_code" class="form-control" placeholder="Canadian or American" maxlength="10" required id="id_zip_code" value="{{ hospital.zip_code }}"><br/>
                    </div>
                </div>
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="phone" class="form-label">
                            Phone
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" name="phone" class="form-control" placeholder="234-567-8901" maxlength="12" required id="id_phone" value="{{ hospital.phone }}"><br/>
                    </div>
                </div>
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="type" class="form-label">
                            Type
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" name="type" class="form-control" placeholder="Public/Private/Nonprofit" maxlength="9" required id="id_type" value="{{ hospital.type }}"><br/>
                    </div>
                </div>
                <div class="row g-3 align-items">
                    <div class="col-auto">
                        <label for="email" class="form-label">
                            Email
                        </label>
                    </div>
                    <div class="col-12">
                        <input type="text" name="email" class="form-control" placeholder="someone@example.ca" maxlength="50" required id="id_email" value="{{ hospital.email }}"><br/>
                    </div>
                </div>
                <input type="hidden" name="pk" value="{{ hospital.name }}">
                <button type="submit" class="btn btn-secondary" value="Cancel" name="cancel"><i class="bi bi-x-square"></i> Cancel</button>
                <button type="submit" class="btn btn-success" value="Update" name="update"><i class="bi bi-floppy"></i> Update</button>
            </form>
        </fieldset>
    </div>
{% endblock content %}